@startuml
left to right direction

actor "Thành viên" as TV
actor "Nhân viên" as NV
TV <|-- NV

usecase "Đăng nhập" as DN
usecase "NV đăng nhập" as NVDN
usecase "Đăng ký tay đua\ntham gia chặng đua" as UC
usecase "Chọn chặng và đội" as UC1
usecase "Chọn tay đua đăng ký" as UC2

TV -- DN
NV -- UC

DN <|-- NVDN
UC ..> NVDN : <<include>>
UC ..> UC1 : <<include>>
UC ..> UC2 : <<include>>
@enduml
